nguage: node_js
node_js:
  - "8.11.4"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn run build

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
