nguage: node_js
node_js:
  - "8.11.4"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn run build

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
